---
- name: Authenticate against Openshift Cluster
  shell: | 
    oc login {{ openshift_master }} --token={{ openshift_token }}

- name: Remove existing oc project
  ignore_errors: yes 
  vars:
      ansible_command_timeout: 2
  shell: | 
    nohup oc delete project {{ openshift_projectname }} &
    sleep 5s

- name: Add external repository and create project
  delay: 3
  retries: 10
  register: result
  until: result.rc == 0
  shell: | 
    oc new-project {{ openshift_projectname }}
    oc delete secret external-registry
    oc secrets new-dockercfg external-registry \
    --docker-username={{ docker_registry_username }} \
    --docker-password={{ docker_registry_password }} \
    --docker-email=aymen@x0r.sh \
    --docker-server={{ docker_registry_url }}
    oc project {{ openshift_projectname }}
    oc secrets add serviceaccount/default secrets/external-registry --for=pull

- name: Deploy openapi sample
  shell: | 
    oc import-image {{ docker_registry_url }}/openapi-cxf-osgi-mock:latest
    oc tag {{ docker_registry_url }}/openapi-cxf-osgi-mock:latest openapi-cxf-osgi-mock --scheduled
    (cd /tmp && curl -O https://raw.githubusercontent.com/aymenfurter/openshift-templates/master/trun.template)
    oc process -f /tmp/trun.template -p SERVICE_NAME=openapi-cxf-osgi-mock | oc create -f -
#    oc new-app --docker-image={{ docker_registry_url }}/openapi-cxf-osgi-mock:latest
   # 
#oc new-app --docker-image=reg.x0r.sh/talendmockws:latest
#oc import-image talendmockws
#oc tag reg.x0r.sh/talendmockws:latest talendmockws --scheduled
#oc secrets new-dockercfg external-registry \
#    --docker-username={{ docker_registry_username }} \
#    --docker-password={{ docker_registry_password }} \
#    --docker-email=aymen@x0r.sh \
#    --docker-server={{ docker_registry_url

# http://openapi-cxf-osgi-mock-integration-test.7e14.starter-us-west-2.openshiftapps.com/services